INFO:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:==== args = {'yaml_config_file': 'config/fedml_config.yaml', 'run_id': '0', 'rank': 0, 'local_rank': 0, 'node_rank': 0, 'role': 'client', 'yaml_paths': ['config/fedml_config.yaml'], 'training_type': 'cross_silo', 'scenario': 'horizontal', 'using_mlops': False, 'random_seed': 0, 'bootstrap': None, 'dataset': 'Cora', 'data_cache_dir': './github/funnyFL/GCN/data', 'partition_method': None, 'partition_alpha': None, 'model': 'lr', 'model_file_cache_folder': './model_file_cache', 'global_model_file_path': './model_file_cache/global_model.pt', 'federated_optimizer': 'FedAvg', 'client_id_list': '[1, 2]', 'client_num_in_total': 1, 'client_num_per_round': 2, 'comm_round': 10, 'epochs': 1, 'batch_size': 10, 'client_optimizer': 'sgd', 'learning_rate': 0.03, 'weight_decay': 0.001, 'frequency_of_the_test': 1, 'worker_num': 2, 'using_gpu': False, 'gpu_mapping_file': 'config/gpu_mapping.yaml', 'gpu_mapping_key': 'mapping_default', 'backend': 'MQTT_S3', 'mqtt_config_path': '', 's3_config_path': '', 'enable_wandb': False, 'n_proc_in_silo': 1, 'proc_rank_in_silo': 0, 'comm': None, 'enable_cuda_rpc': False, 'cpu_transfer': False, 'process_id': 0, 'sys_perf_profiling': True, 'config_version': 'release', 'current_running_dir': '/home/cjlsdsg/fedml-client', 'os_name': 'Linux', 'version': 'release', 'log_file_dir': '/home/cjlsdsg/fedml-server/fedml/logs', 'device_id': '0xd85ed30fb618', 'cloud_region': '', 'log_server_url': 'https://open.fedml.ai/fedmlLogsServer/logs/update'}
ERROR:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:Uncaught exception
Traceback (most recent call last):
  File "/home/cjlsdsg/github/funnyFL/GCN/gcn.py", line 11, in <module>
    dataset = data_load(args)
  File "/home/cjlsdsg/github/funnyFL/GCN/data/citation_networks.py", line 8, in data_load
    if args.dataset in citation_network_name:
AttributeError: 'tuple' object has no attribute 'dataset'
INFO:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:==== args = {'yaml_config_file': 'config/fedml_config.yaml', 'run_id': '0', 'rank': 0, 'local_rank': 0, 'node_rank': 0, 'role': 'client', 'yaml_paths': ['config/fedml_config.yaml'], 'training_type': 'cross_silo', 'scenario': 'horizontal', 'using_mlops': False, 'random_seed': 0, 'bootstrap': None, 'dataset': 'Cora', 'data_cache_dir': './github/funnyFL/GCN/data', 'partition_method': None, 'partition_alpha': None, 'model': 'lr', 'model_file_cache_folder': './model_file_cache', 'global_model_file_path': './model_file_cache/global_model.pt', 'federated_optimizer': 'FedAvg', 'client_id_list': '[1, 2]', 'client_num_in_total': 1, 'client_num_per_round': 2, 'comm_round': 10, 'epochs': 1, 'batch_size': 10, 'client_optimizer': 'sgd', 'learning_rate': 0.03, 'weight_decay': 0.001, 'frequency_of_the_test': 1, 'worker_num': 2, 'using_gpu': False, 'gpu_mapping_file': 'config/gpu_mapping.yaml', 'gpu_mapping_key': 'mapping_default', 'backend': 'MQTT_S3', 'mqtt_config_path': '', 's3_config_path': '', 'enable_wandb': False, 'n_proc_in_silo': 1, 'proc_rank_in_silo': 0, 'comm': None, 'enable_cuda_rpc': False, 'cpu_transfer': False, 'process_id': 0, 'sys_perf_profiling': True, 'config_version': 'release', 'current_running_dir': '/home/cjlsdsg/fedml-client', 'os_name': 'Linux', 'version': 'release', 'log_file_dir': '/home/cjlsdsg/fedml-server/fedml/logs', 'device_id': '0xd85ed30fb618', 'cloud_region': '', 'log_server_url': 'https://open.fedml.ai/fedmlLogsServer/logs/update'}
INFO:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:fedml init ~ 
INFO:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:devide_type = cpu, gpu_mapping_file = None, gpu_mapping_key = None, gpu_id = None
INFO:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:args = <fedml.arguments.Arguments object at 0x7fa23634ddc0>, using_gpu = False, device_id = None, device_type = cpu
INFO:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:Training on device: cpu
INFO:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:device = cpu
ERROR:/home/cjlsdsg/fedml-server/fedml/logs/fedml-run-0-edge-0.log:Uncaught exception
Traceback (most recent call last):
  File "/home/cjlsdsg/github/funnyFL/GCN/gcn.py", line 15, in <module>
    dataset = data_load(args)
  File "/home/cjlsdsg/github/funnyFL/GCN/data/citation_networks.py", line 8, in data_load
    if args.dataset in citation_network_name:
AttributeError: 'tuple' object has no attribute 'dataset'
